server {
    listen 80;
    server_name 192.168.122.1;

    location /docs/ {
        alias /var/www/html/docs/;
        autoindex on;
        client_max_body_size 200m;
        dav_methods PUT;
        dav_access user:rw group:rw all:r;
    }
}
